name: Azure Login

on:
  push:
    branches:
      - main

jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      run: |
        az login --service-principal -u bc93195c-5f0b-488f-87ee-553a3607baac -p b6C8Q~HhQ1hbYSr4oectrSKt~1y_34COQy5fwcbI --tenant bc93195c-5f0b-488f-87ee-553a3607baac
        az account set --subscription f5ef5936-e3ba-4200-ad92-bd9832b5a0ba
