name: 'Terraform'
on:
  push:
     branches:
       - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'Terraform'
 
    run:
     shell: bash
     working-directory: terraform
  steps:
  - name: checkout
    uses: actions/checkout@v2
  - name: 'isntall prereq'
    run: |
     curl -SL "https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip" --output terraform.zip
     unzip "terraform.zip"
     terraform --version
     rm terrafrom.zip
