name: 'Terraform'
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'terraform'
    defaults:
      run:
        shell: bash
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: 'install prereq'
      run: |
        curl -SL "https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip" --output terraform.zip
        unzip "terraform.zip"
        sudo mv terraform /usr/local/bin  # Use sudo to move to /usr/local/bin
        terraform --version
        rm terraform.zip  # Fix the typo in the file name here
